### PR TITLE
Autostart on boot

### PR DESCRIPTION
**Pull request by CMurtagh-LGTM**
I created a unit file that will tell systemd to automatically start timelord on boot.

### CODE REVIEW

**Comment by LachlanCourt** [comment]
Timelord should already start on boot with a cronjob, the problem was the computer itself didn't restart after a power outage lmao. Idk if this is necessary, is there a benefit to this over a bash script?

**Comment by CMurtagh-LGTM** [comment]
The computer did not start Timelord when it was powered on.
I don't see any cron configuration for Timelord on the computer (`10.1.0.197`).
For this, I reckon that is better to manage autostarting on boot with a unit file rather than a cron job.

**Comment by TrentHouliston** [comment]
Cron is crappy old tech, systemd unit file is shiny new tech

**Review by LachlanCourt — APPROVED** [review]
If it works then lgtm, can't test this myself until next week :)

**Comment by CMurtagh-LGTM** [comment]
It has been tested.

**Pull request merged**
